# Configuração do Supabase

# Permitir requisições públicas (sem autenticação)
[functions]

[functions."webhooks-mercadopago"]
verify_jwt = false

[functions."criar-pagamento"]
verify_jwt = false

[functions."consultar-pagamento"]
verify_jwt = false

[functions."calcular-frete-melhor-envio"]
verify_jwt = false
